### ISSUE TITLE
Help for setting parameters

### ISSUE THREAD

**Issue by Mcouedel** [cduvallet/q2-dbotu#1]
Hi !
I wanted to thank you for developing this very useful plugin in Qiime2!
I am trying to use it in my pipeline but I think I am not setting it right. I would like to group my ASVs at 99% without the size being taken into account in the output of DADA2. I added a step to cut my primers before to run dbOTU. I have coded it like this:

`qiime dbotu-q2 call-otus 
    --i-table 4-table-COI.qza 
    --i-sequences 4-rep-seqs-COI.qza 
    --p-gen-crit 0.01 
    --p-abund-crit 10.0 
    --p-pval-crit 0.0005 
    --o-representative-sequences 5-dbotu01-seqs-COI.qza 
    --o-dbotu-table 5-dbotu01-table-COI.qza 
    --verbose > membership-COI-file.txt`

However, on output I still have completely identical reads (not detected in DADA2 because of the primers). I think the problem comes from my clustering parameters which take into account the abundance. What can I do?
Thank you for your help!
Cheers
Marion

**Comment by cduvallet** [comment]
Hi! I am not longer actively working in the microbiome field, so I probably won't be of much help to you here. I recommend asking your question on the qiime2 forum, where others may be able to help. (I also have an account on the forum and can try to take a look if nobody is able to help). Best of luck!
